name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  CLOJURE_CLI_VERSION: "1.11.1.1165"
  BB_VERSION: "0.9.162"
  ZPRINT_VERSION: "1.2.3"
  CLJ_KONDO_VERSION: "2022.09.08"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          bb: ${{env.BB_VERSION}}
          zprint: ${{env.ZPRINT_VERSION}}
          clj-kondo: ${{env.CLJ_KONDO_VERSION}}

      - name: Run checks
        run: bb check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          bb: ${{env.BB_VERSION}}
          cli: ${{env.CLOJURE_CLI_VERSION}}

      - name: Download dependencies
        run: bb deps

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            $HOME/.m2/repository
            $GITHUB_WORKSPACE/.cpcache
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure

      - name: Run tests
        run: bb test
